/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SEMANA12;

import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
class node {

    int dato;
    node sgte;
    node ant;

    public node(int n) {
        this.dato = n;
        sgte = ant = null;
    }

    int tostring() {
        return this.dato;
    }
}

class metodos {

    node inicio;
    node fin;

    public metodos() {
        inicio = fin = null;
    }

    void ingresar(int n) {
        node newnodo = new node(n);
        if (inicio == null) {
            inicio = fin = newnodo;
        } else {
            fin.sgte = newnodo;
            newnodo.ant = fin;
            fin = newnodo;
        }
    }

    String mostrar() {
        String cad = "";
        node temp = inicio;
        while (temp != null) {
            cad += temp.tostring() + "\n";
            temp = temp.sgte;
        }
        return cad;
    }

    void insertar(int n, int p) {
        node newnodo = new node(n);
        node temp1 = null, temp2 = null;
        if (inicio != null) {
            temp1 = inicio;
            temp2 = temp1.sgte;
        }
        int i = 1;
        if (p > (nodosize() + 1)) {
            JOptionPane.showMessageDialog(null, "Fuera de rango!!");
        } else {
            if (p < 0) {
                JOptionPane.showMessageDialog(null, "Se ingreso un Rango Negativo!!");
            } else {
                if (p == 1) {
                    inicio.ant = newnodo;
                    newnodo.sgte = inicio;
                    inicio = newnodo;
                } else {
                    if (p == nodosize() + 1) {
                        fin.sgte = newnodo;
                        newnodo.ant = fin;
                        fin = newnodo;
                    } else {
                        while (temp1 != null) {
                            //System.out.println("entro");
                            if (i == (p - 1)) {
                                temp1.sgte = newnodo;
                                temp2.ant = newnodo;
                                newnodo.ant = temp1;
                                newnodo.sgte = temp2;
                                break;
                            }
                            temp1 = temp1.sgte;
                            temp2 = temp1.sgte;
                            i++;
                        }
                    }
                }
            }

        }

    }

    int nodosize() {
        int x = 0;
        node temp = inicio;
        while (temp != null) {
            temp = temp.sgte;
            x++;
        }
        return x;
    }
}

public class eje08 extends javax.swing.JFrame {

    metodos ope;

    /**
     * Creates new form eje08
     */
    public eje08() {
        initComponents();
        ope = new metodos();
        btninsertar.setEnabled(false);
        txtposicion.setEnabled(false);
        txtnumero.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbnumero = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtanumeros = new javax.swing.JTextArea();
        lbposicion = new javax.swing.JLabel();
        btninsertar = new javax.swing.JButton();
        txtposicion = new javax.swing.JTextField();
        lbnelementos = new javax.swing.JLabel();
        lbnroelementos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbnumero.setText("Número:");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        txtanumeros.setColumns(20);
        txtanumeros.setRows(5);
        jScrollPane1.setViewportView(txtanumeros);

        lbposicion.setText("Posicion");

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        lbnelementos.setText("Elementos: ");

        lbnroelementos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnumero)
                            .addComponent(lbposicion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtposicion)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbnelementos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbnroelementos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btninsertar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmostrar)))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnumero)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar)
                    .addComponent(btnmostrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbposicion)
                    .addComponent(txtposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninsertar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbnelementos)
                            .addComponent(lbnroelementos))
                        .addGap(38, 38, 38)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        int n;
        if (txtnumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese numero a ingresar a la lista!!");

        } else {
            n = Integer.parseInt(txtnumero.getText());
            ope.ingresar(n);
            btninsertar.setEnabled(true);
            txtposicion.setEnabled(true);
        }

        txtnumero.setText("");
        txtnumero.requestFocus();
        lbnroelementos.setText(String.valueOf(ope.nodosize()));

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        txtanumeros.setText(ope.mostrar());
        txtnumero.setText("");
        txtnumero.requestFocus();
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
        int n, p;
        if (txtnumero.getText().equals("") | txtposicion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingresar el numero y la posicion de la lista!!");
        } else {
            n = Integer.parseInt(txtnumero.getText());
            p = Integer.parseInt(txtposicion.getText());
            ope.insertar(n, p);
        }

        txtanumeros.setText(ope.mostrar());
        txtnumero.setText("");
        txtposicion.setText("");
        txtnumero.requestFocus();
        lbnroelementos.setText(String.valueOf(ope.nodosize()));
    }//GEN-LAST:event_btninsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje08().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbnelementos;
    private javax.swing.JLabel lbnroelementos;
    private javax.swing.JLabel lbnumero;
    private javax.swing.JLabel lbposicion;
    private javax.swing.JTextArea txtanumeros;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtposicion;
    // End of variables declaration//GEN-END:variables
}
